### ISSUE TITLE
如何使用ant-move 转换最新版的  Vant-Weapp 

### ISSUE THREAD

**Issue by zhanyeye** [ant-move/Vant-Aliapp#10]
因为 Vant-Weapp 有不少的更新，所有想请问，可以自己将 Vant-Weapp 转换为 Vant-Aliapp 吗？
在文档中没有找到，所以来问一下啊😀

**Comment by martianyi** [comment]
vant-aliapp已跟进到vant-weapp 1.6.2版, 可以通过npm下载最新版试用
