### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by y274013840** [ant-move/Vant-Aliapp#12]
Error: /pages/components/vant-app/dist/stepper/index.json
component custom-input => /__antmove/component/custom-input/custom-input 不存在
或 /__antmove/component/custom-input/custom-input.json 中没有申明 "component: true" 
或其他异常

**Comment by martianyi** [comment]
我们正在修复，请先回退到1.0.15版本

**Comment by martianyi** [comment]
1.0.18 已修复，可以升级到1.0.18版本
