### ISSUE TITLE
Cannot read property 'mountedHandles' of undefined

### ISSUE THREAD

**Issue by ZachGuoMingyu** [ant-move/Vant-Aliapp#6]
引入Vant后使用组件会报这个错误

**Comment by xiaofuzi** [comment]
开启 component2 编译模式

**Comment by ZachGuoMingyu** [comment]
> 开启 component2 编译模式

vant可以在钉钉小程序里使用吗

**Comment by bruce-dumbledore** [comment]
怎么解决这个错误

**Comment by xiaofuzi** [comment]
开启 component2 编译模式

**Comment by bruce-dumbledore** [comment]
1. 

> 开启component2编译模式

![微信截图_20200518143302](https://user-images.githubusercontent.com/37292247/82181117-7e904080-9914-11ea-9abb-d6e8f78b7794.png)
我这里没看到 component2  在哪里呀

**Comment by xiaofuzi** [comment]
钉钉小程序？

**Comment by bruce-dumbledore** [comment]
> 钉钉小程序？

恩恩 对的 难道不能用vant吗

**Comment by xiaofuzi** [comment]
是按照这个文档引入的吗 https://ant-move.github.io/guide/contribute/ddUseAntmove.html#%E4%BB%8B%E7%BB%8D
